firm:
  public:
    controller:     'public'
    views:          'trst'
    layout:         'layout'
    page:
      title:        'Waste Management Ltd.'
      header:       'WSTM motto'
      footer_text:  '&copy; 2005-2016 Waste Management Ltd.'
      footer_title: 'Ferenc-Loránt Kiss'
  system:
    page:
      title:        'TrustSys - Wstm'
      header:       'TrustSys wstm'
      footer_text:  '&copy; 2005-2016 kfl62'
      footer_title: 'Ferenc-Loránt Kiss'

  sass_dir:     'system/assets/stylesheets'
  css_dir:      'public/stylesheets'
  css_path:     '/stylesheets'
  css_file:     'wstm.css'
  images_dir:   'public/images/wstm'
  images_path:  '/images/wstm'
  i18n_path:    'wstm'
  js_path:      'wstm'

  models_path:  [trst, wstm]
  db_devel:     'trst_wstm'
  db_test:      'trst_test'
  db_prod:      'trst_wstm'
